name: CI to Docker Hub
on:
  push:
    paths:
      - 01-representacion_de_datos/Dockerfile
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: 01-representacion_de_datos/
          file: 01-representacion_de_datos/Dockerfile
          push: true
          tags: orgacomp/01:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
